version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
    - "3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: admin

  mighty:
    image: supermon/mighty
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - db
    links:
    - db

  front:
    image: supermon/sample-front-mighty
    restart: always
    ports:
    - 8000:8000
    depends_on:
    - mighty
    links:
    - mighty
